skinparam {
    ActorBackgroundColor darkviolet
    ActorBorderColor grey
    ActorFontColor white
    ArrowColor deepskyblue
    ArrowFontColor black
    BoxBackgroundColor black
    BoxBorderColor grey
    BackgroundColor #f0f0f0
    DatabaseBackgroundColor white
    DatabaseBorderColor deeppink
    DatabaseFontColor black
    LifeLineBorderColor grey
    LifeLineBackgroundColor grey
    NoteBackgroundColor white
    NoteBorderColor lime
    NoteFontColor black
    SequenceDividerBackgroundColor white
    SequenceDividerBorderColor white
    SequenceDividerFontColor black
    SequenceGroupBackgroundColor deepskyblue
    SequenceGroupBorderColor grey
    SequenceGroupFontColor orangered
    SequenceGroupHeaderBackgroundColor orangered
    SequenceGroupHeaderBorderColor grey
    SequenceGroupHeaderFontColor black
    SequenceLifeLineBorderColor deeppink
    ParticipantBackgroundColor white
    ParticipantBorderColor deeppink
    ParticipantFontColor black
    StateBackgroundColor darkturquoise
    StateBorderColor grey
    StateFontColor white
    TitleBackgroundColor white
    TitleBorderColor black
    TitleFontColor black
    DefaultFontColor black   
}
