skinparam {
    ActorBackgroundColor darkviolet
    ActorBorderColor grey
    ActorFontColor white
    ArrowColor white
    ArrowFontColor white
    BoxBackgroundColor black
    BoxBorderColor grey
    BackgroundColor black
    DatabaseBackgroundColor deepskyblue
    DatabaseBorderColor grey
    DatabaseFontColor white
    LifeLineBorderColor grey
    LifeLineBackgroundColor grey
    NoteBackgroundColor lime
    NoteBorderColor grey
    NoteFontColor black
    SequenceDividerBackgroundColor white
    SequenceDividerBorderColor white
    SequenceDividerFontColor white
    SequenceGroupBackgroundColor deepskyblue
    SequenceGroupBorderColor grey
    SequenceGroupFontColor orangered
    SequenceGroupHeaderBackgroundColor orangered
    SequenceGroupHeaderBorderColor grey
    SequenceGroupHeaderFontColor black
    SequenceLifeLineBorderColor grey
    ParticipantBackgroundColor deeppink
    ParticipantBorderColor black
    ParticipantFontColor white
    StateBackgroundColor darkturquoise
    StateBorderColor grey
    StateFontColor white
    SwimlaneBackgroundColor grey
    SwimlaneBorderColor grey
    SwimlaneFontColor black
    TitleBackgroundColor white
    TitleBorderColor black
    TitleFontColor black
    DefaultFontColor black
    
}
